[package]
name=stop-me
version=0.0.2

[require]
packages=paszlib

[target]
examples=examples/letter_count examples/tests/test_addie \
  examples/tests/test_image examples/tests/test_lfsr
units=addie calendar lfsr perf_measure perf_image prng


[clean]
files=*.bmp *.png *.jpeg $(COMPILER_UNITTARGETDIR)/*.o html_doc/*.css \
  html_doc/*.gif html_doc/*.html html_doc/*.js html_doc/*.png \
  letter_count$(EXEEXT) test_addie$(EXEEXT) test_image$(EXEEXT) \
  test_lfsr$(EXEEXT)

