[package]
name=stop-me
version=0.0.2

[require]
packages=paszlib

[target]
examples=test_addie test_image test_lfsr
units=addie calendar lfsr perf_image prng


[clean]
files=*.bmp *.png *.jpeg $(COMPILER_UNITTARGETDIR)/*.o html_doc/*.css \
  html_doc/*.gif html_doc/*.html html_doc/*.js html_doc/*.png
